// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWT3g73HTwiePpKXDywTs3z4_--2_C0zU',
    appId: '1:684329885216:web:fe77d493c10d3eaa032645',
    messagingSenderId: '684329885216',
    projectId: 'visitcounter-fef16',
    authDomain: 'visitcounter-fef16.firebaseapp.com',
    databaseURL: 'https://visitcounter-fef16-default-rtdb.firebaseio.com',
    storageBucket: 'visitcounter-fef16.appspot.com',
    measurementId: 'G-WNB3QKWVJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnPKku92cGBcHTse1ijISUT8sZwpOVGY',
    appId: '1:684329885216:android:db436e499cc135e5032645',
    messagingSenderId: '684329885216',
    projectId: 'visitcounter-fef16',
    databaseURL: 'https://visitcounter-fef16-default-rtdb.firebaseio.com',
    storageBucket: 'visitcounter-fef16.appspot.com',
  );
}
